version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      # ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
