name: Push new version to dist branch
on:
  push:
    branches:
      - main
  # pull_request:
  # branches:
  # - main

jobs:
  deploy:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
      - name: yarn install and build
        run: |
          yarn
          yarn workspace @spicetify/marketplace build:prod

      - run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Push new version
        env:
          SRC_FOLDER: "packages/marketplace/dist"
          TARGET_BRANCH: "dist"
        run: |
          files=$(find $SRC_FOLDER -type f)
          git config --global user.name "Github Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git fetch
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD || git commit -am "Update dist to output generated at $SHORT_SHA"
          git push origin $TARGET_BRANCH
