name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: New version number
        required: true
        type: string

jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump Package Version
        run: npm version --no-git-tag-version ${{ github.event.inputs.new_version }}
      - name: Commit Changes
        run: |
          git commit -am "chore: bump version to ${{ github.event.inputs.new_version }}"
          git push origin HEAD

  build_and_push:
    name: Build and push
    needs: bump_version
    uses: ./.github/workflows/push.yml

  create_release:
    name: Create release
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Download "dist" branch
        run: curl -s -o spicetify-marketplace.zip https://codeload.github.com/${{ github.repository }}/zip/refs/heads/dist
      - name: Publish Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ github.event.inputs.new_version }}
          generate_release_notes: true
          files: spicetify-marketplace.zip
